apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ops
  namespace: biz
  labels:
    app: k8s-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ops
  template:
    metadata:
      labels:
        app: k8s-ops
    spec:
      containers:
      - name: k8s-ops
        image: uhub.service.ucloud.cn/safehouse/k8s-ops:v0.0.3
        ports:
        - containerPort: 8080
